# Generated by Django 3.2.13 on 2022-06-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220613_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.folder'),
        ),
    ]
